// Code generated by counterfeiter. DO NOT EDIT.
package healthfakes

import (
	"context"
	"sync"

	v1 "github.com/nginx/agent/v3/api/grpc/mpi/v1"
)

type FakeHealthWatcherOperator struct {
	HealthStub        func(context.Context, *v1.Instance) (*v1.InstanceHealth, error)
	healthMutex       sync.RWMutex
	healthArgsForCall []struct {
		arg1 context.Context
		arg2 *v1.Instance
	}
	healthReturns struct {
		result1 *v1.InstanceHealth
		result2 error
	}
	healthReturnsOnCall map[int]struct {
		result1 *v1.InstanceHealth
		result2 error
	}
	SetConnectedStub        func(bool)
	setConnectedMutex       sync.RWMutex
	setConnectedArgsForCall []struct {
		arg1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHealthWatcherOperator) Health(arg1 context.Context, arg2 *v1.Instance) (*v1.InstanceHealth, error) {
	fake.healthMutex.Lock()
	ret, specificReturn := fake.healthReturnsOnCall[len(fake.healthArgsForCall)]
	fake.healthArgsForCall = append(fake.healthArgsForCall, struct {
		arg1 context.Context
		arg2 *v1.Instance
	}{arg1, arg2})
	stub := fake.HealthStub
	fakeReturns := fake.healthReturns
	fake.recordInvocation("Health", []interface{}{arg1, arg2})
	fake.healthMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeHealthWatcherOperator) HealthCallCount() int {
	fake.healthMutex.RLock()
	defer fake.healthMutex.RUnlock()
	return len(fake.healthArgsForCall)
}

func (fake *FakeHealthWatcherOperator) HealthCalls(stub func(context.Context, *v1.Instance) (*v1.InstanceHealth, error)) {
	fake.healthMutex.Lock()
	defer fake.healthMutex.Unlock()
	fake.HealthStub = stub
}

func (fake *FakeHealthWatcherOperator) HealthArgsForCall(i int) (context.Context, *v1.Instance) {
	fake.healthMutex.RLock()
	defer fake.healthMutex.RUnlock()
	argsForCall := fake.healthArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeHealthWatcherOperator) HealthReturns(result1 *v1.InstanceHealth, result2 error) {
	fake.healthMutex.Lock()
	defer fake.healthMutex.Unlock()
	fake.HealthStub = nil
	fake.healthReturns = struct {
		result1 *v1.InstanceHealth
		result2 error
	}{result1, result2}
}

func (fake *FakeHealthWatcherOperator) HealthReturnsOnCall(i int, result1 *v1.InstanceHealth, result2 error) {
	fake.healthMutex.Lock()
	defer fake.healthMutex.Unlock()
	fake.HealthStub = nil
	if fake.healthReturnsOnCall == nil {
		fake.healthReturnsOnCall = make(map[int]struct {
			result1 *v1.InstanceHealth
			result2 error
		})
	}
	fake.healthReturnsOnCall[i] = struct {
		result1 *v1.InstanceHealth
		result2 error
	}{result1, result2}
}

func (fake *FakeHealthWatcherOperator) SetConnected(arg1 bool) {
	fake.setConnectedMutex.Lock()
	fake.setConnectedArgsForCall = append(fake.setConnectedArgsForCall, struct {
		arg1 bool
	}{arg1})
	stub := fake.SetConnectedStub
	fake.recordInvocation("SetConnected", []interface{}{arg1})
	fake.setConnectedMutex.Unlock()
	if stub != nil {
		fake.SetConnectedStub(arg1)
	}
}

func (fake *FakeHealthWatcherOperator) SetConnectedCallCount() int {
	fake.setConnectedMutex.RLock()
	defer fake.setConnectedMutex.RUnlock()
	return len(fake.setConnectedArgsForCall)
}

func (fake *FakeHealthWatcherOperator) SetConnectedCalls(stub func(bool)) {
	fake.setConnectedMutex.Lock()
	defer fake.setConnectedMutex.Unlock()
	fake.SetConnectedStub = stub
}

func (fake *FakeHealthWatcherOperator) SetConnectedArgsForCall(i int) bool {
	fake.setConnectedMutex.RLock()
	defer fake.setConnectedMutex.RUnlock()
	argsForCall := fake.setConnectedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeHealthWatcherOperator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.healthMutex.RLock()
	defer fake.healthMutex.RUnlock()
	fake.setConnectedMutex.RLock()
	defer fake.setConnectedMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHealthWatcherOperator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
